# Generated by Django 2.2.2 on 2021-09-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='indication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.indication'),
        ),
        migrations.AlterField(
            model_name='application',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.product'),
        ),
    ]
