# Generated by Django 2.2.2 on 2021-09-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20210907_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.app_type'),
        ),
    ]
